#!/bin/sh

if [ $# -ne 1 ]; then
    echo "Usage: create <repo path>"
    exit 1
fi

. /env.sh

repo_paths=`find $GIT_REPO_ROOT -type d -name '*.git'`

new_repo=$1

raw_new_repo_path="$GIT_REPO_ROOT/$new_repo"

new_repo_path=`realpath -m "$raw_new_repo_path"`

if [ "$raw_new_repo_path" != "$new_repo_path" -o "${new_repo_path:(-4)}" != ".git" ]; then
    echo "Repository must be in the format \"[<namespace>/]+<repository name>.git\""
    exit 1
fi

for repo_path in $repo_paths; do
    if [ "$repo_path" = "$new_repo_path" ]; then
        echo "Repository with this name already exists"
        exit 1
    fi
done

git init --bare $new_repo_path
