#!/bin/sh

if [ $# -ne 1 ]; then
    echo "Usage: create <repo path>"
    exit 1
fi

. /env.sh

repo_paths=`find $GIT_REPO_ROOT -type d -name '*.git'`

new_repo=$1

raw_new_repo_path="$GIT_REPO_ROOT/$new_repo"

new_repo_path=`realpath -m "$raw_new_repo_path"`

if [ "$raw_new_repo_path" != "$new_repo_path" -o "${new_repo_path:(-4)}" != ".git" -o "${new_repo_path:(-5)}" = "/.git" ]; then
    echo "Repository must be in the format \"[<namespace>/]+<repository name>.git\""
    exit 1
fi

for repo_path in $repo_paths; do
    if [ "$repo_path" = "$new_repo_path" ]; then
        echo "Repository with this name already exists"
        exit 1
    fi
done

git init --bare $new_repo_path > /dev/null

# Creates a first commit to omit the empty repository warning and problems with the default branch (that otherwise would
# fall back to "master" instead of the preferred "main"
git clone --quiet $new_repo_path /tmp/repo > /dev/null 2>&1
cd /tmp/repo 
touch .gitignore 
git add . 
git commit --quiet -m "Repository initialization" 
git push --quiet 
cd - > /dev/null
rm -rf /tmp/repo/


