#!/bin/sh

if [ $# -ne 0 ]; then
    echo "Usage: list"
    exit 1
fi

. /env.sh

repos=`find $GIT_REPO_ROOT -type d -name '*.git' | cut -d '/' -f 4- | sort`

max_length=`echo $repos | tr " " "\n" | wc -L`

for repo in $repos; do
    printf "%-${max_length}s  %s\n" $repo "git clone ssh://git@$GIT_HOST_HINT/$repo"
done
